task_manager/statuses/urls.py
from django.urls import path
from task_manager.statuses import views


app_name = 'statuses'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.createStatus, name='create'),
    path('<int:pk>/delete/', views.deleteStatus, name='delete'),
    path('<int:pk>/update/', views.editStatus, name='edit'),
]

task_manager/tasks/urls.py
from django.urls import path
from task_manager.tasks import views


app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.createTask, name='create'),
    path('<int:pk>/update/', views.editTask, name='edit'),
    path('<int:pk>/delete/', views.deleteTask, name='delete'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('', include('django.contrib.auth.urls'), name='login'),
]

task_manager/users/urls.py
from django.urls import path, include
from task_manager.users import views


app_name = 'users'

urlpatterns = [
    # path('', views.index),
    path('', views.index, name='index'),
    path('add/', include('django.contrib.auth.urls')),
    # path('create/', views.addUser),
    path('create/', views.SignUpView.as_view(), name='create'),
]

task_manager/statuses/models.py
from django.db import models

class Status(models.Model):
    name = models.CharField(max_length=100, unique=True)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)

task_manager/tasks/models.py
from django.db import models
from task_manager.users.models import User
from task_manager.statuses.models import Status

class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    author = models.ForeignKey(User, related_name='author', on_delete=models.PROTECT)
    executor = models.ForeignKey(User, related_name='executor', on_delete=models.CASCADE)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)

task_manager/users/models.py
from django.db import models


class User(models.Model):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

task_manager/statuses/forms.py
from django import forms
from task_manager.statuses import models


class CreateStatusForm(forms.ModelForm):
    class Meta:
        model = models.Status
        fields = ('name',)

task_manager/tasks/forms.py
from django import forms
from task_manager.tasks import models


class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = ('title', 'description', 'author',
                'executor', 'status')

task_manager/users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from task_manager.users.models import User

class AddUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')

    def clean_first_name(self):
        name = self.cleaned_data['first_name']
        if len(name) > 10:
            raise ValidationError('Длина не должна превышать 10 символов')

        return name

task_manager/statuses/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from task_manager.statuses.forms import CreateStatusForm
from task_manager.statuses.models import Status


def index(request):
    statuses = Status.objects.all()
    return render( request, 'statuses/index.html', {'statuses': statuses})


def createStatus(request):
    if request.method == 'POST':
        form = CreateStatusForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/statuses')
    else:
        form = CreateStatusForm()

    return render(request, 'statuses/create.html', {'form': form})


def deleteStatus(request, pk):
    status = Status.objects.get(id=pk)
    form = CreateStatusForm(instance=status)
    if request.method == 'POST':
        status.delete()
        return HttpResponseRedirect('/statuses')

    return render(request, 'statuses/delete.html', {'status': status, 'form': form})



def editStatus(request, pk):
    status = Status.objects.get(id=pk)
    form = CreateStatusForm(instance=status)

    if request.method == 'POST':
        status.name = request.POST.get('name')
        status.save()
        return HttpResponseRedirect('/statuses')
    else:
        return render(request, 'statuses/edit.html', {'status': status, 'form': form})

task_manager/tasks/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from task_manager.tasks.forms import CreateTaskForm
from task_manager.tasks.models import Task
from task_manager.users.models import User
from task_manager.statuses.models import Status


def index(request):
    tasks = Task.objects.all()
    return render(request, 'tasks/index.html', {'tasks': tasks})


def createTask(request):
    if request.method == 'POST':
        form = CreateTaskForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/tasks')
    else:
        form = CreateTaskForm()

    return render(request, 'tasks/create.html', {'form': form})


def editTask(request, pk):
    task = Task.objects.get(id=pk)
    form = CreateTaskForm(instance=task)

    if request.method == 'POST':
        author = User.objects.get(id=request.POST.get('author'))
        executor = User.objects.get(id=request.POST.get('executor'))
        status = Status.objects.get(id=request.POST.get('status'))

        task.title = request.POST.get('title')
        task.description = request.POST.get('description')
        task.author = author
        task.executor = executor
        task.status = status

        task.save()
        # form = CreateTaskForm(request.POST)
        # form.save()
        return HttpResponseRedirect('/tasks')

    return render(request, 'tasks/create.html', {'form': form, 'task': task})


def deleteTask(request, pk):
    task = Task.objects.get(id=pk)
    form = CreateTaskForm(instance=task)
    if request.method == 'POST':
        task.delete()
        return HttpResponseRedirect('/tasks')

    return render(request, 'tasks/delete.html', {'task': task, 'form': form})

task_manager/users/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from django.http import HttpResponseRedirect
from task_manager.users.forms import AddUserForm
from task_manager.users.models import User

from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/create.html'

def addUser(request):
    if request.method == 'POST':
        form = AddUserForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/users')
    else:
        form = AddUserForm()

    return render(request, 'users/create.html', { 'form': form })

def index(request):
    users = User.objects.all()
    session = request.session
    print(session)
    return render(request, 'users/index.html', { 'users': users})

# class ListUser(ListView):
#     model = User


from django.contrib.auth.models import User

def addAuthUser(request):
    # Создайте пользователя и сохраните его в базе данных
    user = User.objects.create_user('xz', 'jopa@crazymail.com', 'mypassword')

    # Обновите поля и сохраните их снова
    user.first_name = 'John'
    user.last_name = 'Citizen'
    user.save()

task_manager/templates/index.html
{% load bootstrap4 %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!doctype html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>{% translate "Task manager" %}</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery=True %}

  </head>
  <body>
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">{% translate "Home" %} <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:index' %}">{% translate "Users" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'statuses:index' %}">{% translate "Statuses" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tasks:index' %}">{% translate "Tasks" %}</a>
        </li>
      </ul>

      <a class="p-2 text-dark" href="{% url 'login' %}">{% translate "Login" %}</a>
      <a class="btn btn-outline-primary" href="{% url 'users:create' %}">{% translate "Sign up" %}</a>
    </div>
  </nav>

  <main role="main">
    <div class="jumbotron">
      <div class="col-sm-8 mx-auto">
        {% block content %}
        <h1>Navbar examples</h1>
        <p>This example is a quick exercise to illustrate how the navbar and its contents work. Some navbars extend the width of the viewport, others are confined within a <code>.container</code>. For positioning of navbars, checkout the <a href="/docs/4.5/examples/navbar-static/">top</a> and <a href="/docs/4.5/examples/navbar-fixed/">fixed top</a> examples.</p>
        <p>At the smallest breakpoint, the collapse plugin is used to hide the links and show a menu button to toggle the collapsed content.</p>
        <p>
          <a class="btn btn-primary" href="/docs/4.5/components/navbar/" role="button">View navbar docs »</a>
        </p>
        {% endblock %}
      </div>
    </div>
  </main>
</div>

<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">{% translate "Footer" %}</span>
  </div>
</footer>

</body>
</html>

task_manager/templates/statuses/create.html
{% extends "../index.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}
<form method='post'>
{% csrf_token %}
{% bootstrap_form form %}
{% translate 'Save' as save_translate %}
{% bootstrap_button save_translate button_type="submit" button_class="btn-primary" %}
</form>
{% endblock %}

task_manager/templates/statuses/delete.html
{% extends "../index.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}
<form method='post'>
{% csrf_token %}
<p>Вы уверены, что хотите удалить статус {{ status.name}}?</p>
<!-- {% bootstrap_form form %} -->
{% translate 'Yes, delete' as yes_delete_translate %}
{% bootstrap_button yes_delete_translate button_type="submit" button_class="btn-primary" %}
</form>
{% endblock %}

task_manager/templates/statuses/edit.html
{% extends "../index.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}
<form method='post'>
{% csrf_token %}
{% bootstrap_form form %}
{% translate 'Save' as save_translate %}
{% bootstrap_button save_translate button_type="submit" button_class="btn-primary" %}
</form>
{% endblock %}

task_manager/templates/statuses/index.html
{% extends "../index.html" %}
{% load i18n %}

{% block content %}
Статусы: {{ statuses }}
<ul>
{% for status in statuses %}
<li>{{ status.id }} {{ status.name }} <a href="{% url 'statuses:delete' status.id %}">{% translate 'Delete' %}</a> <a href="{% url 'statuses:edit' status.id %}">{% translate 'Edit' %}</a></li>
{% endfor %}
</ul>

<p><a href="{% url 'statuses:create' %}">{% translate 'Add status' %}</a></p>
{% endblock %}

task_manager/templates/tasks/create.html
{% extends "../index.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}
<form method='post'>
{% csrf_token %}
{% bootstrap_form form %}
{% translate 'Save' as save_translate %}
{% bootstrap_button save_translate button_type="submit" button_class="btn-primary" %}
</form>
{% endblock %}

task_manager/templates/tasks/delete.html
{% extends "../index.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}
<form method='post'>
{% csrf_token %}
<p>Вы уверены, что хотите удалить задачу <b>"{{ task.description }}"</b>?</p>
<!-- {% bootstrap_form form %} -->
{% translate 'Yes, delete' as yes_delete_translate %}
{% bootstrap_button yes_delete_translate button_type="submit" button_class="btn-primary" %}
</form>
{% endblock %}

task_manager/templates/tasks/index.html
{% extends "../index.html" %}
{% load i18n %}

{% block content %}
Задачи: {{ tasks }}
{% for task in tasks %}
<h2> {{ task.title }} <small>{{ taks.id }}</small></h2>
<p>{{ task.description }}</p>
<p>Автор - {{ task.author }}, исполнитель - {{ task.executor }}</p>
<p>
<a href="{% url 'tasks:delete' task.id %}">{% translate 'Delete' %}</a>
<a href="{% url 'tasks:edit' task.id %}">{% translate 'Edit' %}</a>
</p>
{% endfor %}

<p><a href="{% url 'tasks:create' %}">{% translate 'Add task' %}</a></p>
{% endblock %}

task_manager/templates/users/create.html
{% extends "../index.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}
<h2>Sign Up</h2>

<p>
{{ user }}
<br>--<br>
{% if user.is_authenticated %}
hi, {{ user.username}}<br>

{% else %}

<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% translate 'Sign up' as sign_up_translate %}
  {% bootstrap_button sign_up_translate button_type="submit" button_class="btn-primary" %}
</form>
{% endif %}
</p>
{% endblock %}

task_manager/templates/users/index.html
{% extends "../index.html" %}

{% block content %}
User: {{ user }}
<ul>
{% for user in users %}
<li>{{ user.email }} – {{ user.first_name }} {{ user.last_name }}</li>
{% endfor %}
</ul>
{% endblock %}